### ISSUE TITLE
Trail Page

### ISSUE THREAD

**Issue by mappingsa** [mappingsa/macrivertrails#1]
When navigating to a trail page the image is missing and the text is not formatted properly.

**Comment by mappingsa** [comment]
This seems to be effected now that 
jquery.mobile.simultaneous-transitions-replace-simple and jquery.mobile.transition-handler-simple have been commented out, I'm guessing that this has been done to fix the back button. 
Added these 2 back into a debug build and the trail page images load fine but back button doesn't work.

**Comment by mappingsa** [comment]
Image loading in ios but text is not formatted left  as in toptal original build jquery.mobile.simultaneous-transitions-replace-simple and jquery.mobile.transition-handler-simple

**Comment by daniel-g** [comment]
This error is fixed here https://github.com/mappingsa/macrivertrails/pull/8

**Comment by mappingsa** [comment]
Thanks Daniel
