### ISSUE TITLE
directions map then back 

### ISSUE THREAD

**Issue by mappingsa** [mappingsa/macrivertrails#4]
when you have set directions on the map page and you navigate back to the map page, the trail page list is sitting over the top of the map page ( have screenshot to show this)

**Comment by mappingsa** [comment]
Some weird stuff happening here in regards to navigating back, seems pages are loading over the top of other pages, not hard to produce this issue.
Ok so I un commented  just the jquery.mobile.simultaneous-transitions-replace-simple in debug and this seems to have fixed the loading over the top of other pages issue, back button still works but Trail pages and now place page have image not loading issues.
This issue seems to be tied to the jquery.mobile.transition-handler-simple and jquery.mobile.simultaneous-transitions-replace-simple being commented as well.

**Comment by daniel-g** [comment]
I don't see the screenshot, but it seems to be fixed here https://github.com/mappingsa/macrivertrails/pull/8

**Comment by mappingsa** [comment]
fixed
