### ISSUE TITLE
No distances from your current location

### ISSUE THREAD

**Issue by mappingsa** [mappingsa/macrivertrails#6]
On the map page there are no distances showing when you press the green tab, this is supposed to show a list of sorted trails from the closest to the furthest. When the tab slides up there is no way to remove it and get back to the map.

**Comment by mappingsa** [comment]
This was part of the old app so it needs to be added back in.

**Comment by mappingsa** [comment]
Error in debug on chrome "Uncaught TypeError: Cannot read property 'length' of undefined" show marker list markersLength = markers.length

Also (anonymous function) showMarkerList()

**Comment by daniel-g** [comment]
I cannot reproduce, I don't get this error.

**Comment by mappingsa** [comment]
The list view is still not showing, when you press the nearby tab and navigate to the map page there is a green tab, when you click or press the green tab a list is supposed to slide up giving you a list view over the map showing you trail distances from your current location. 
Best we discuss this issue if your not sure

**Comment by daniel-g** [comment]
the list should show the shortest distance first from your current location

**Comment by mappingsa** [comment]
Thanks Daniel works great
